name: Bump Package Version On Merge

on:
  push:
    branches:
      - main

jobs:
  bump-package-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 16
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major"
          patch-wording: "patch,fixes"
          rc-wording: "RELEASE,alpha"
          default: prerelease
          tag-prefix: "v."
          target-branch: "main"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
