name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Node.js dependencies
      run: npm install

    - name: Install ESLint
      run: |
        npm install eslint
        npm install @microsoft/eslint-formatter-sarif

    - name: Continuous Integration
      run: npm ci

    - name: Run ESLint
      run: eslint . --ext .ts,.tsx
